mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                path('polls/', include(('polls.urls','polls'),namespace="polls")),
                path('admin/', admin.site.urls),
                ]

mysite/polls/urls.py
from django.urls import path
from . import views


urlpatterns = [
            path('index/', views.index,name="ticker"),
            path('index/add/<str:fav>/', views.favoriteAdd,name="favorites"),
            path('index/<str:ticker>/',views.quickLink,name="link"),
            path('frontpage/signup/', views.signup,name="signup"),
            path('frontpage/', views.frontpage,name="frontpage"),
            path('frontpage/login/', views.loginUser,name="login"),
            path('frontpage/favorites/', views.favoriteList,name="list"),
            path('frontpage/logout/', views.logoutUser,name="logout"),
            path('frontpage/insert/', views.insert,name="insert"),
            path('frontpage/about/', views.about,name="about"),
            path('frontpage/advancedsearch/', views.formset_view,name="advanced")
            ]

mysite/polls/models.py
from django.db import models


class Data(models.Model):
    key = models.AutoField(primary_key=True)
    ticker = models.TextField(blank=True, null=True)
    high = models.DecimalField(blank=True, null=True,decimal_places=2,max_digits=2)
    low = models.DecimalField(blank=True, null=True,decimal_places=2,max_digits=2)
    median = models.DecimalField(blank=True, null=True,decimal_places=2,max_digits=2)
    percentage = models.TextField(blank=True, null=True)
    lastprice = models.DecimalField(blank=True, null=True,decimal_places=2,max_digits=2)
    annalyst = models.DecimalField(blank=True, null=True,decimal_places=2,max_digits=2)
    date = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'data'


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class Favorites(models.Model):
    ticker = models.TextField(blank=True, null=True)
    currentuser = models.ForeignKey(AuthUser, models.DO_NOTHING, db_column='currentuser')

    class Meta:
        managed = False
        db_table = 'favorites'

mysite/polls/forms.py
from django import forms
from polls.models import AuthUser
from django.contrib.auth import authenticate


def updateEmail():
	email = AuthUser.objects.values('email')
	validateEmail = []
	for x in email:
		validateEmail.append(x['email'])
	return validateEmail


def updateUsername():
	username = AuthUser.objects.values('username')
	validateUsername = []
	for x in username:
		validateUsername.append(x['username'])
	return validateUsername


indicator = [
    ('high', 'Estimated High'),
    ('low', 'Estimated Low'),
    ('median', 'Estimated Median'),
    ('lastprice', 'Real Price'),
    ]


symbol= [
    ('__gt', 'higher than'),
    ('__lt', 'less than'),
    (' ', 'equal to'),
    ]


class InitialSearch(forms.Form):
    primary = forms.ChoiceField(label='' ,choices=indicator)
    symbol =  forms.ChoiceField(label='' ,choices=symbol)
    secondary = forms.ChoiceField(label='',choices=indicator)
    today = forms.BooleanField(initial=False)

class Search(forms.Form):
    primary = forms.ChoiceField(label='' ,choices=indicator)
    symbol =  forms.ChoiceField(label='' ,choices=symbol)
    secondary = forms.ChoiceField(label='',choices=indicator)

class SignUp(forms.Form):
	email = forms.EmailField(label='email',widget=forms.EmailInput(attrs={'class':'form-control form-control-lg ','placeholder': 'Email'}))
	username = forms.CharField(label='username', max_length=100,widget=forms.TextInput(attrs={'class':'form-control form-control-lg ','placeholder': 'UserName'}))
	fname = forms.CharField(label='FirstName', max_length=100,widget=forms.TextInput(attrs={'class':'form-control form-control-lg ','placeholder': 'First Name'}))
	password = forms.CharField(label='password', max_length=100,widget=forms.PasswordInput(attrs={'class':'form-control form-control-lg ','placeholder': 'Password'}))
	lname = forms.CharField(label='LastName', max_length=100,widget=forms.TextInput(attrs={'class':'form-control form-control-lg ','placeholder': 'Last Name'}))
		
	def clean_email(self):
		validateEmail = updateEmail()
		data = self.cleaned_data['email']
		if data in validateEmail:
			raise forms.ValidationError('This email address is already in use.')
		return data
	
	def clean_username(self):
		validateUsername = updateUsername()
		data = self.cleaned_data['username']
		if data in validateUsername:
			raise forms.ValidationError('This username is already in use.')
		return data


class InsertTicker(forms.Form):
	ticker = forms.CharField(label='username', max_length=10,widget=forms.TextInput(attrs={'class':'form-control form-control-lg ','placeholder': 'Ticker ID'}))


class Login(forms.Form):
	username = forms.CharField(label='username', max_length=100,widget=forms.TextInput(attrs={'class':'form-control form-control-lg ','placeholder': 'Email or Username'}))
	password = forms.CharField(label='password', max_length=100,widget=forms.PasswordInput(attrs={'class':'form-control form-control-lg ','placeholder': 'Password'}))
	
	def clean(self):
		cleanUsername = self.cleaned_data['username']
		user = authenticate(username=cleanUsername, password=self.cleaned_data['password'])
		if(user is None):
			email = AuthUser.objects.filter(email = cleanUsername).first()	
			if(email is None):
				raise forms.ValidationError("Username or password incorrect. Please enter again")
			user = authenticate(username=email.username, password=self.cleaned_data['password'])
			if(user is None):
				raise forms.ValidationError("Username or password incorrect. Please enter again")
			self.cleaned_data['username'] = email.username
		return 
		

mysite/polls/views.py
from curses.ascii import SI
from sre_constants import SUCCESS
from django.db.models import Func
from django.db.models.functions import Round
from django.shortcuts import render
from django.http import  HttpResponseRedirect
import psycopg2
from django.contrib import messages 
from django.shortcuts import redirect
from polls.forms import SignUp, Login, InsertTicker, Search
from polls.models import Data, AuthUser, Favorites
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import subprocess
from django.db.models import F, Q
from django.forms import formset_factory 
from django.db.models import Max
from datetime import date

conn = psycopg2.connect(host="localhost", port="5432", dbname="project", user="sal", password="password")


class Round(Func):
    function = 'ROUND'
    template='%(function)s(%(expressions)s, 2)'


def arrayConverter(dict):
    ans1 = []
    for row in dict:
        ans1.append((row[0]))
    return ans1


def extractBasicStockData(stock):
    cur = conn.cursor()
    cur.execute("select * from data where ticker like %s order by date desc", [stock])
    store = cur.fetchone()
    barChart = []
    barChart.append(store[2])
    barChart.append(store[3])
    barChart.append(store[4])
    return barChart


def convertFrontPageTableLists(a):
    ans = []
    for row in a:
        print(row)
        store = []
        store.append((row[0]))
        store.append((row[1]))
        ans.append(store)
    ans.reverse()
    return ans

def frontpageStartUp():
    cur = conn.cursor()
    cur.execute("select distinct ticker from data order by ticker asc;")
    a = cur.fetchall()
    ans1 = arrayConverter(a)

    cur.execute("select ticker, max(high) from data where date = Current_date group by ticker order by max(high) desc limit 10;")
    query = cur.fetchall()
    ans2 = convertFrontPageTableLists(query)

    cur.execute("select ticker, max(lastprice) from data where date = Current_date group by ticker order by max(lastprice) desc limit 10;")
    query = cur.fetchall()
    ans3 = convertFrontPageTableLists(query)

    cur.execute("select ticker, max(annalyst) from data where date = Current_date group by ticker order by max(annalyst) desc limit 10;")
    query = cur.fetchall()
    ans4 = convertFrontPageTableLists(query)

    cur.execute("select ticker, replace(substr(percentage,2),',','')::DECIMAL as perc from data where date = current_date order by perc desc limit 10;")
    query = cur.fetchall()
    ans5 = convertFrontPageTableLists(query)

    cur.execute("select ticker,max(low) from data where date = current_date group by ticker order by max(low) desc limit 10;")
    query = cur.fetchall()
    ans6 = convertFrontPageTableLists(query)

    cur.execute("select ticker, min(high) from data where date = Current_date group by ticker order by min(high) asc limit 10;")
    query = cur.fetchall()
    ans7 = convertFrontPageTableLists(query)

    cur.execute("select ticker, min(lastprice) from data where date = Current_date group by ticker order by min(lastprice) asc limit 10;")
    query = cur.fetchall()
    ans8 = convertFrontPageTableLists(query)

    cur.execute("select ticker, min(annalyst) from data where date = Current_date group by ticker order by min(annalyst) asc limit 10;")
    query = cur.fetchall()
    ans9 = convertFrontPageTableLists(query)

    cur.execute("select ticker, replace(substr(percentage,2),',','')::DECIMAL as perc from data where date = current_date order by perc asc limit 10;")
    query = cur.fetchall()
    ans10 = convertFrontPageTableLists(query)

    cur.execute("select ticker,min(low) from data where date = current_date group by ticker order by min(low) asc limit 10;")
    query = cur.fetchall()
    ans11 = convertFrontPageTableLists(query)

    return ans1,ans2,ans3,ans4,ans5,ans6,ans7,ans8,ans9,ans10,ans11


def frontpage(request):
    stocks = frontpageStartUp()
    return render(request,"frontpage.html",{"languages":stocks[0],"highEstimate":stocks[1],"highRealprice":stocks[2], \
    "highAnnalyst":stocks[3],"highPercentage":stocks[4],"highLow":stocks[5],"lowEstimate":stocks[6],"lowRealPrice":stocks[7], \
    "lowAnnalyst":stocks[8], "lowPercentage":stocks[9],"lowLow":stocks[10]})


def signup(request):
    form = SignUp(request.POST)
    if request.method == 'POST':
        user_form = SignUp(data=request.POST)
        if(user_form.is_valid()):
            insert = AuthUser(first_name=user_form.cleaned_data['fname'],last_name=user_form.cleaned_data['lname'],email=user_form.cleaned_data['email'],
            username=user_form.cleaned_data['username'],password=make_password(user_form.cleaned_data['password']),is_superuser = False,is_staff=False,is_active= True,date_joined=timezone.now())
            insert.save()
            user = authenticate(request, username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password'])
            return redirect('polls:login')
        else:
            return render(request,"signup.html",{"form":form})
    form = SignUp()
    return render(request,"signup.html",{"form":form})


def formset_view(request):
    context ={}
    GeeksFormSet = formset_factory(Search,extra = 1)
    formset = GeeksFormSet(request.POST or None)
    results = False
    if formset.is_valid():
        counter = 0
        Qr = None
        for form in formset:
            if(form.cleaned_data['symbol'] == ' '):
                a = form.cleaned_data['primary']
            else:
                a = form.cleaned_data['primary'] + form.cleaned_data['symbol']
            q = Q(**{"%s" % a:F(form.cleaned_data['secondary'])})
            counter += 1
            if Qr:
                Qr = Qr & q # or & for filtering
            else:
                Qr = q
            formset = GeeksFormSet()

        primary = form.cleaned_data['primary']
        symbol = form.cleaned_data['symbol']
        secondary = form.cleaned_data['secondary']

        # today = form.cleaned_data['today']
        # if(today == True):
        #     Qr = Qr & Q(date = date.today())
        if(symbol == '__lt'):
            results = Data.objects.filter(Qr).values('ticker').annotate(Max('date'),Max('lastprice'),Max('median'),Max('low'),Max('high'),store=Round((Max(F(secondary))-Max(F(primary))))).order_by('ticker')        
        elif(symbol == '__gt'):
            results = Data.objects.filter(Qr).values('ticker').annotate(Max('date'),Max('lastprice'),Max('median'),Max('low'),Max('high'),store=Round((Max(F(primary))-Max(F(secondary))))).order_by('ticker')
        elif(symbol == ' '):
            results = Data.objects.filter(Qr).values('ticker').annotate(Max('date'),Max('lastprice'),Max('median'),Max('low'),Max('high'),store=Round((Max(F(primary))-Max(F(secondary))))).order_by('ticker')
        print(results.query)
        if results:
            return render(request, "advancedsearchGraph.html",{"results":results})
        elif(results is not False and len(results) == 0):
            messages.error(request, "Search returned zero results")
        
    context['formset']= formset
    return render(request, "advancedsearch.html", context)


def loginUser(request): 
    form = Login(request.POST)
    if request.method == 'POST':
        user_form = Login(data = request.POST)
        if(user_form.is_valid()):
            user = authenticate(request, username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password'])
            login(request,user)
            return redirect('polls:frontpage')
        else:
            return render(request,"login.html",{"form":form})
    form = Login()
    return render(request,"login.html",{"form":form})


def logoutUser(request):
    logout(request)
    return redirect('polls:frontpage')


@login_required(login_url='polls:signup')
def favoriteAdd(request,fav):
    a = AuthUser(id = request.user.id)    
    filter = Favorites.objects.filter(ticker = fav, currentuser = request.user.id)
    if(filter):
        filter.delete()
        messages.success(request, "Removed " + fav + " from favorites list.")
    else:
        here = Favorites(ticker = fav,currentuser = a)
        here.save()
        messages.success(request, "Added " + fav + " into your favorites list.")
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required(login_url='polls:signup')
def favoriteList(request):
    cur = conn.cursor()
    list = Favorites.objects.filter(currentuser = request.user.id)
    fixedFavoriteList = []
    for row in list:
        fixedStock = []
        cur.execute("select * from data where ticker like %s order by date desc", [row.ticker])
        stockData = cur.fetchone()
        fixedStock.append(row.ticker)
        fixedStock.append(stockData[2])
        fixedStock.append(stockData[3])
        fixedStock.append(stockData[4])
        fixedStock.append(stockData[6])
        fixedFavoriteList.append(fixedStock)
    return render(request,"favorites.html",{"list":fixedFavoriteList})


def index(request):
    cur = conn.cursor()
    stock = None
    if request.method == 'GET':
        stock = request.GET['searchbar'].upper()
    filter = Favorites.objects.filter(ticker = request.GET['searchbar'].upper(), currentuser = request.user.id)
    cur.execute("select * from data where ticker like %s order by date desc", [stock])
    store = cur.fetchone()
    barChart = []
    barChart.append(store[2])
    barChart.append(store[3])
    barChart.append(store[4])
    rating = store[9]
    annalysts = store[7]
    cur.execute("select * from data where ticker like %s order by date desc", [stock])
    store = cur.fetchall()
    lineGraph = [[],[],[],[],[]]
    for day in store:
        lineGraph[0].append(day[2])
        lineGraph[1].append(day[3])
        lineGraph[2].append(day[4])
        lineGraph[3].append(day[6])
        lineGraph[4].append(day[8].strftime("%m/%d/%Y"))

mysite/polls/templates/about.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <body>
        <div class = "container-fluid pt-3 px-4" style="max-width:850px">
            <div class = "col-12" >
                <div class = "row mt-2">
                    <div class = "title d-flex justify-content-center border-bottom border-dark" id = "title">About</div>
                </div>
                <div class = "row mt-2">
                    <p class = "lead flex d-flex justify-content-center">The purpose of this website is to check CNN's estimation of stocks over time. All data is webscraped using bash. 
                        A stock's price should overtime hover near its median estimate, and so by webscraping CNN's estimation of various stocks, this website will check 
                        whether or not CNN's estimations are valid.</p>
                    <div class = "row flex justify-content-center mt-5">
                        <div class = "col">
                            <div class="card" style="width: 20rem;">
                                <div class="card-body text-center" >
                                    <h5 class="card-title">Number of Stocks Tracked</h5>
                                    <p class="card-text">{{number}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="card" style="width: 20rem;">
                            <div class="card-body text-center" >
                                <h5 class="card-title">Total Number of Records</h5>
                                <p class="card-text">{{total}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    </html>
</body>
</html>
{% endblock %}

mysite/polls/templates/advancedSearchGraph.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class = "container " >
        <div class = "row" >
            <div class = "col-12" >
                <div class = "row pt-3 mb-5">
                    <div class = "title d-flex justify-content-center border-bottom border-dark" id = "title">Results</div>
                </div>
            </div>
            
        </div>
    </div>
    <div class = "container " style="max-width:850px" >
        <table id="table" class="display" width = "100%"></table>
    </div>
<script>
    var store = [];
        "{% for stock in results %}"
            store.push([link("{{ stock.ticker }}"),"{{ stock.store }}","{{ stock.high__max }}","{{ stock.low__max }}","{{stock.median__max}}","{{stock.lastprice__max}}","{{stock.date__max}}"]);    
        "{% endfor %}"
        var tabledata = [];
        for(var x in store){
            tabledata.push([(store[x][0]), "$"+store[x][1],"$"+store[x][2], "$"+store[x][3], "$"+store[x][4],"$"+store[x][5],store[x][6]]);
        }
    $(document).ready( function () {

        var dataSet = tabledata;
            $(document).ready(function () {
                $('#table').DataTable({
                  
                    "rowCallback": function( row, data ) {
                    },
                    
                    data: dataSet,
                    columns: [
                        { title: 'Ticker',"width": "10%" },
                        { title: 'Difference',"width": "1%" },
                        { title: 'High Estimate',"width": "1%" },
                        { title: 'Low Estimate.',"width": "1%" },
                        { title: 'Median Price',"width": "1%"},
                        { title: 'Real Price',"width": "1%"},
                        { title: 'Latest Date of occurence',"width": "1%"},
                        
                    ],
                });
            });
    });
    function link(url){
        return "<a style =\"color:black\" href='/polls/index/"+url+"' >"+url+"</a>";
    }
</script>
</body>
</html>
{% endblock %}

mysite/polls/templates/stock.html
{% extends "layout.html" %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    
    <a href={% url 'polls:favorites' stock %} id = "link" ></a>
    <style type="text/css" >
        .chartBox{
            width: 1000px;
            margin:auto;
        }
    </style>
    <meta id="stock" data-name="{{stock}}">
    <meta id="high" data-name="{{high}}">
    <meta id="low" data-name="{{low}}">
    <meta id="median" data-name="{{median}}">  
  </head>

  <body>
    <div class="container-fluid" style = "max-width: 1550px" >
      <div class="row pt-4 text-center" style = "margin:auto">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      </div> 
      <div class = "row" style="text-align:center">
        <div class = "col">
          {% if rating|stringformat:'s' == "Buy" %}
            <span class="bi bi-arrow-up" data-toggle="tooltip" data-placement="top" title="Buy Rating from {{annalysts}} annalysts" style='cursor:pointer;font-size:42px; color:rgb(15, 153, 21);'></span>
          {% elif rating|stringformat:'s' == "Sell" %}
            <span class="bi bi-arrow-down" data-toggle="tooltip" data-placement="top" title="Sell Rating from {{annalysts}} annalysts" style='cursor:pointer;font-size:42px; color:rgb(199, 15, 15);'></span>
          {% elif rating|stringformat:'s' == "Outperform" %}
            <span data-toggle="tooltip" data-placement="top" title="Outperform Rating from {{analysts}} annalysts" style='font-size:48px;color:rgb(81, 240, 88);'>&#8673;</span>
          {% elif rating|stringformat:'s' == "Underperform" %}
          <span data-toggle="tooltip" data-placement="top" title="Underperform Rating from {{annalysts}} annalysts" style='font-size:48px;color:rgb(214, 62, 62);'>&#8675;</span>
          {% elif rating|stringformat:'s' == "Hold" %}
          <span class="bi bi-circle-fill" data-toggle="tooltip"  data-placement="top" title="Hold Rating from {{annalysts}} annalysts" style='font-size:40px;color:rgb(119, 119, 119);'></span>
          {% endif %}
          <label for="star" id = "fav" data-url={% url 'polls:favorites' stock %}  class="custom-checkbox" > 
            {{ stock }}
            {% if filter %}
              <input type="checkbox" id="star" checked/>
            {% else %}
              <input type="checkbox" id="star"/>
            {% endif %}
              <i class="bi bi-star-fill"></i>
              <i class="bi bi-star"></i>
          </label>
        </div>
      </div>
      <div class="row flex justify-content-center" >
        <!--Grid column-->
        <div class = "col-md-2" style = "visibility: hidden;" >
        </div>
        <div class="col-6 pt-2" >
          <div id="header"><a href="https://money.cnn.com/quote/forecast/forecast.html?symb={{stock}}" style = "color:black">{{stock}}'s</a> stock price has been less than or equal to its low estimate for <b>{{ list.lesser }}</b> days, higher than or equal to its high estimate for 
            <b>{{ list.greater }}</b> days, and in between its low and high estimate for <b>{{ list.middle }}</b> days. <br>
          </div> 
        </div>
        <!--Grid column-->
        <div class = "col-md-2 pull-right" style = "width:300px;" >
          <canvas id="pie-chart"></canvas>
      </div>
    </div>
  </div>

    <div class="container-fluid" style="max-width:1100px; ">
   
      <div class = "row mb-5" style = "margin:0;">
        <div class = "col mb-3">
          <div class = "chartBox">
            <canvas id="myChart"></canvas> 
          </div>
        </div>
        <div class = "row">
          <div class = "chartBox" >
            <canvas id="barChart"></canvas>
          </div>
        </div>
      </div>
    </div>
  </body>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})


  const ctx = document.getElementById('myChart').getContext('2d');
  const dtx = document.getElementById('barChart').getContext('2d');
  var stock = document.getElementById("stock").getAttribute('data-name');
  var high = "{{barChart.0}}";
  var low = "{{barChart.1}}";
  var median = "{{barChart.2}}";

  var lineHigh = "{{lineGraph.0|safe}}";
  lineHigh = lineHigh.replaceAll("'", "").replaceAll("[","").replaceAll("]","").replaceAll(" ","");
  lineHigh = lineHigh.split(",");
 
  console.log(lineHigh)
  var lineLow = "{{lineGraph.1}}";
  lineLow = lineLow.replaceAll("'", "").replaceAll("[","").replaceAll("]","").replaceAll(" ","");
  lineLow = lineLow.split(",");
  var lineMedian = "{{lineGraph.2}}";
  lineMedian = lineMedian.replaceAll("'", "").replaceAll("[","").replaceAll("]","").replaceAll(" ","");
  lineMedian = lineMedian.split(",");
  var real = "{{lineGraph.3}}";
  real = real.replaceAll("'", "").replaceAll("[","").replaceAll("]","").replaceAll(" ","");
  real = real.split(",");
  var lineDate = "{{lineGraph.4|safe}}";
  lineDate = lineDate.replaceAll("'", "").replaceAll("[","").replaceAll("]","").replaceAll(" ","");
  lineDate = lineDate.split(",");


  $('#fav').click(function() {
    var url = $("#fav").attr("data-url");
    document.location.href = url
  });


const barChart = new Chart(dtx, {
    type: 'bar',
    
    data: {
        labels: ['High Estimate', 'Low Estimate', 'Median Estimate'],
        datasets: [{
            label: 'Stock Price',
            data: [high, low, median],
            fillOpacity: .3,
            backgroundColor: [
                "#1FA82A",
                '#FF0000',
                "#0000FF",
            ],
            borderColor: [
                "#1FA82A",
                '#FF0000',
                "#0000FF",
            ],
            fillOpacity : .3,
            borderWidth: 2
        }]
    },
    options: {
        scales: {
          y: {
                ticks: {
                    // Include a dollar sign in the ticks
                    callback: function(value, index, ticks) {
                        return '$' + value;
                    }
                }
            }
        },
        legend: {
            display: false
        },  
        plugins: {
            title: {
              font: {
                size: 25
              },
            fontStyle: 'bold',
            display: true,
            text: 'Today\'s Price Forecast for ' + stock
            }
        }
    }
});

options: {
        
    }
const myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: lineDate,
    datasets: [{ 
        data: lineHigh,
        label: "High Estimate",
        borderColor: "#1FA82A",
        fill: false
      }, { 
        data: lineLow,
        label: "Low Estimate",
        borderColor: "#FF0000",
        fill: false
      }, { 
         data: real,
         label: "Real Price",
         borderColor: "#000000",
         fill: false
       }, 
       { 
         data: lineMedian,
         label: "Median Estimate",
         borderColor: "#0000FF",
         fill: false
       },
    ]
  },
  options: {
    plugins:{
            title: {
                font: {
                  size: 25
                },
                fontStyle: 'bold',
                display: true,
                text: 'CNN Prediction of ' + stock + " over time"
            }
        },
    scales: {
        y: {
          ticks: {
              // Include a dollar sign in the ticks
              callback: function(value, index, ticks) {
                  return '$' + value;
              }
          }
      }
   }
  }
});

new Chart(document.getElementById("pie-chart"), {
    type: 'pie',
    data: {
      labels: ["Higher than High Estimate", "Lower than Low Estimate", "Between High and Low Estimates"],
      datasets: [{
        label: "Population (millions)",
        backgroundColor: ["#1FA82A", "#FF0000","#0000FF"],
        data: ["{{list.greater}}","{{list.lesser}}","{{list.middle}}"]
      }]
    },
    options: {
      title: {
        display: true,
        
      }
    }
});

</script>
</html>
{% endblock %}